### ISSUE TITLE
Comparing TR vs EPYC 

### ISSUE THREAD

**Issue by Ragebone** [PSPReverse/PSPTool#7]
hello,
started looking at the UEFis of the two following boards and  noticed some interesting differences that could be correlated to the  platform attributes that i haven't seen discussed or visibly detected in the output of the psptool.

https://www.asrockrack.com/general/productdetail.asp?Model=X399D8A-2T#Specifications
https://www.asrockrack.com/general/productdetail.asp?Model=EPYCD8-2T#Specifications

Looking at the contained non empty paddings, both have two. 
The first padding in both is filled with FF until about 20000h where the Epyc one contains the only non FF values:
`aa55 aa55 0000 0000 0000 0000 0010 02ff
0000 0000 0070 07ff 0070 11ff`

And the X399 has: 
`aa55 aa55 0000 0000 0000 0000 0010 02ff
0000 0000 0070 0aff 0070 13ff 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0070 2fff 0000 0000`

With a few FFs followed by a LOT of Stuff.
Binwalk won't detect any signatures or instructions inside that first padding.

What is up with that?
The only reasonable explanation a friend and me could come up with so far is that the mentioned Bytes are some kind of Platform ID and the following data on x399 is for the Chipset.
Did i miss this in the psptool output somehow?

Proceeding with a binwalk of the second non empty padding, a 
`1802924       0x1B82AC        CRC32 polynomial table, little endian`
and on another asrock X399MT, a 
`1906350       0x1D16AE        Unix path: /Code/AMD/platform/NVMem.c` 
differ from the Epyc part. 

Binwalking for instructions, the second padding on both x399 contains only ARM entrys where as the Eypc contains an additional ARMBE entry. 

Any ideas on what the frick is going on?
Sincerely Norman

**Comment by cwerling** [comment]
Hi Norman,

what you see is the Firmware Entry Table. It is denoted by the magic bytes `AA55AA55` and the starting point for PSPTools parsing logic. Here are two related figures of mine documenting the PSP Firmware File System:

<img width="300" alt="Bildschirmfoto 2019-08-29 um 15 22 14" src="https://user-images.githubusercontent.com/8776698/63943901-d928fa00-ca70-11e9-95cd-4e7c89fb6f67.png">

<img width="367" alt="Bildschirmfoto 2019-08-29 um 15 22 23" src="https://user-images.githubusercontent.com/8776698/63943948-ed6cf700-ca70-11e9-96e5-6f72900a4c66.png">

Its contents are represented by a `Blob` object in PSPTool. You can discover the structure a bit better using the psptool Python module in a Python shelll like IPython:

```python
In [1]: from psptool import PSPTool

In [2]: epyd = PSPTool.from_file('EPYD82T1.50')

In [3]: x39d = PSPTool.from_file('X39D82T1.00')

In [5]: epyd.blob.firmware_entry_table.get_bytes()
Out[5]: b'\xaaU\xaaU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x02\xff\x00\x00\x00\x00\x00p\x07\xff\x00p\x11\xff'

In [6]: x39d.blob.firmware_entry_table.get_bytes()
Out[6]: b'\xaaU\xaaU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x02\xff\x00\x00\x00\x00\x00p\n\xff\x00p\x13\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p/\xff\x00\x00\x00\x00'

In [7]: epyd.blob
Out[7]: Blob(agesa_version=AGESA!V9 NaplesPI-SP3 1.0.0.9, len(firmwares)=1, len(directories)=4)

In [9]: x39d.blob
Out[9]: Blob(agesa_version=AGESA!V9 ThreadRipperPI-SP3r2-1.1.0., len(firmwares)=2, len(directories)=4)

In [10]: epyd.blob.firmwares
Out[10]: [<Firmware(type=XHCI, address=0x21000, magic=bytearray(b'\xff\xff\xff\xff'))>)]

In [11]: x39d.blob.firmwares
Out[11]:
[<Firmware(type=XHCI, address=0x21000, magic=bytearray(b'\x80\x07\xf8\x00'))>),
 <Firmware(type=unknown, address=0x2f7000, magic=bytearray(b'_PT_'))>)]
```

Firmwares are unparsable by PSPTool, as we haven't looked into them yet. Feel free to find out e.g. header structures and incorporate your findings into PSPTool in order to display information about those. Directories are what you see when using the CLI or `epyd.ls()`.

Cheers,
Christian
